version: '3.1'

services:
    mysql:
        restart: always
        env_file: mysql.development.env
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
           - ./docker/volumes/mysqlvol:/var/lib/mysql
           - ./mysql/sql/food_nutrition-initial.sql.gz:/docker-entrypoint-initdb.d/food_nutrition-initial.sql.gz
    django:
        restart: always
        build: ./cruxOptimWebApp/.
        command: "/usr/local/bin/gunicorn cruxOptimWebApp.wsgi:application -w 1 -b :8000"
        volumes:
            - ./cruxOptimWebApp:/code
        ports:
            - "8000:8000"
        depends_on:
            - mysql
